# Generated by Django 4.2.2 on 2023-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_id', models.CharField(default='', max_length=240, null=True)),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('address', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
