# Generated by Django 4.2.2 on 2023-06-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_grades_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_registration',
            name='city',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='country',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='dateofbirth',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='gender',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='password',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='qualification',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='qualification_cirt',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='state',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='username',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.CreateModel(
            name='Tutor_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=240, null=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tutor_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=240, null=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tutor_registration')),
            ],
        ),
    ]
