# Generated by Django 4.2.2 on 2023-06-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_tutor_registration_city_tutor_registration_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_registration',
            name='status',
            field=models.CharField(default='0', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_registration',
            name='otp',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
