# Generated by Django 4.2.2 on 2023-06-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_tutor_registration_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('parentfullname', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('city', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
