# Generated by Django 4.2.2 on 2023-06-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_student_registration_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='address',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='country',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='dateofbirth',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='gender',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='password',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='state',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='username',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
